[package]
name = "chat_service"
version = "0.1.0"
edition = "2021"

[dependencies]
http-muncher = "0.3.2"
mio = {version = "0.8.10", features = ["os-poll", "net"]}
rustc-serialize = "0.3"
sha1 = "0.10.6"
